const occupations = [
  { value: 0, label: 'Estudante' },
  { value: 1, label: 'Representante do Poder Legislativo e Órgãos Executivos, Diretor, Gerente e Executivo' },
  { value: 2, label: 'Especialista em Atividade Intelectual e Científica' },
  { value: 3, label: 'Técnico de Nível Intermediário e Profissão Intermediária' },
  { value: 4, label: 'Pessoal Administrativo' },
  { value: 5, label: 'Serviço Pessoal, Trabalhador de Segurança e Vendedor' },
  { value: 6, label: 'Agricultor e Trabalhador Qualificado na Agricultura, Pesca e Silvicultura' },
  { value: 7, label: 'Trabalhador Qualificado na Indústria, Construção e Artesão' },
  { value: 8, label: 'Operador de Instalação e Máquina e Trabalhador de Montagem' },
  { value: 9, label: 'Trabalhador Não Qualificado' },
  { value: 10, label: 'Profissão das Forças Armadas' },
  { value: 90, label: 'Outra Situação' },
  { value: 99, label: '(em branco)' },
  { value: 122, label: 'Profissional da Saúde' },
  { value: 123, label: 'Professor' },
  { value: 125, label: 'Especialista em Tecnologia da Informação e Comunicação (TIC)' },
  { value: 131, label: 'Técnico de Nível Intermediário em Ciência e Engenharia' },
  { value: 132, label: 'Técnico e Profissional de Nível Intermediário em Saúde' },
  { value: 134, label: 'Técnico de Nível Intermediário em Serviço Jurídico, Social, Desportivo, Cultural e Similar' },
  { value: 141, label: 'Trabalhador de Escritório, Secretário em Geral e Operador de Processamento de Dados' },
  { value: 143, label: 'Operador de Serviço de Dados, Contabilidade, Estatística, Financeiro e de Registro' },
  { value: 144, label: 'Outro Pessoal de Apoio Administrativo' },
  { value: 151, label: 'Trabalhador de Serviço Pessoal' },
  { value: 152, label: 'Vendedor' },
  { value: 153, label: 'Trabalhador de Cuidado Pessoal e Similar' },
  { value: 171, label: 'Trabalhador Qualificado em Construção e Similar, Exceto Eletricista' },
  { value: 173, label: 'Trabalhador Qualificado em Impressão, Fabrico de Instrumento Preciso, Joalheiro e Similar' },
  { value: 175, label: 'Trabalhador na Indústria de Processamento de Alimento, Madeira, Vestuário e Outra Indústria e Artesanato' },
  { value: 191, label: 'Trabalhador de Limpeza' },
  { value: 192, label: 'Trabalhador Não Qualificado na Agricultura, Produção Animal, Pesca e Silvicultura' },
  { value: 193, label: 'Trabalhador Não Qualificado na Indústria Extrativa, Construção, Fabrico e Transporte' },
  { value: 194, label: 'Assistente de Preparação de Refeição' }
];

export default occupations